Template Datasource Implementation
dell/terraform-provider-powerflex pull request #152
Opened 2024-01-24 08:46 UTC by Krunal-Thakkar

# Description
Template Datasource Implementation

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 80% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-01-24 11:29 UTC, shenda1 commented on powerflex/provider/template_datasource_schema.go
> +				setvalidator.ConflictsWith(
I think only one check of ConflictsWith is fine. Please verify.

2024-01-24 11:32 UTC, shenda1 commented on powerflex/provider/template_datasource.go
> +Copyright (c) 2023 Dell Inc., or its subsidiaries. All Rights Reserved.
2024

2024-01-24 11:34 UTC, shenda1 commented on powerflex/provider/template_datasource_schema.go
> +		"names": schema.SetAttribute{
template_names will make more sense? Thoughts?

2024-01-24 11:35 UTC, shenda1 commented on docs/data-sources/template.md
> +# Copyright (c) 2023 Dell Inc., or its subsidiaries. All Rights Reserved.
2024

2024-01-24 11:41 UTC, shenda1 requested changes
Don't see acceptance tests?

2024-01-24 13:00 UTC, rounak-adhikary commented on powerflex/provider/template_datasource_schema.go
> +		"names": schema.SetAttribute{
IMHO
```terraform
data "powerflex_template" "templates" {
    names = ["temp1", "temp2"]
}
```
looks better than
```terraform
data "powerflex_template" "templates" {
    template_names = ["temp1", "temp2"]
}
```
This is because, within the context of a datasource named `template`, the prefix `template_` feels redundant.

Similarly, to me, `template_ids`  looks clumsier than  `ids`.

2024-01-25 11:32 UTC, Krunal-Thakkar commented on powerflex/provider/template_datasource_schema.go
> +				setvalidator.ConflictsWith(
Updated.

2024-01-29 12:15 UTC, shenda1 submitted a review, later dismissed

2024-01-29 12:16 UTC, Krunal-Thakkar commented
run e2e test

2024-01-29 12:36 UTC, AnikaAgiwal2711 commented on docs/data-sources/template.md
> +# Get template details using template. IDs
Can we change this to "Get template details using the ID of the template."

2024-01-29 13:41 UTC, Krunal-Thakkar commented
run e2e test

2024-01-29 13:41 UTC, AnikaAgiwal2711 approved these changes

2024-01-29 13:43 UTC, shenda1 approved these changes

2024-01-29 13:44 UTC, Krunal-Thakkar commented
run e2e test

2024-01-29 14:05 UTC, Krunal-Thakkar commented
run e2e test

2024-01-30 05:04 UTC, merged