Snapshot policy resource
dell/terraform-provider-powerflex pull request #153
Opened 2024-01-30 12:02 UTC by AnikaAgiwal2711

# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 80% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-01-30 12:16 UTC, terraform-providers-svc commented
Can one of the admins verify this patch?

2024-01-30 19:10 UTC, shenda1 commented on docs/resources/snapshot_policy.md
> +# Copyright (c) 2023 Dell Inc., or its subsidiaries. All Rights Reserved.
2024

2024-01-30 19:11 UTC, shenda1 commented on examples/resources/powerflex_snapshot_policy/resource.tf
> +Copyright (c) 2023 Dell Inc., or its subsidiaries. All Rights Reserved.
2024

2024-01-30 19:13 UTC, shenda1 commented on powerflex/provider/snapshot_policy_resource_test.go
> +Copyright (c) 2023 Dell Inc., or its subsidiaries. All Rights Reserved.
2024

2024-01-30 19:13 UTC, shenda1 commented on powerflex/provider/snapshot_policy_resource.go
> +Copyright (c) 2023 Dell Inc., or its subsidiaries. All Rights Reserved.
2024

2024-01-30 19:15 UTC, shenda1 commented on powerflex/provider/snapshot_policy_resource.go
> +				"Error assigning volume to snapshot policy",
Since this is a new resource, can we handle the partial creation issue?

2024-01-30 19:21 UTC, shenda1 commented on powerflex/provider/snapshot_policy_resource.go
> +				AutoSnapshotRemovalAction: "Detach",
Any reason remove mode is hardcoded here?

2024-01-30 19:21 UTC, shenda1 commented on powerflex/provider/snapshot_policy_resource.go
> +	// upadting the list of volumes assinged to the state
updating

2024-01-30 19:22 UTC, shenda1 commented on powerflex/provider/snapshot_policy_resource.go
> +	for _, v := range volumes {
Since we have a dedicated function for populating state, can this logic be moved to function?

2024-01-30 19:26 UTC, shenda1 commented on powerflex/provider/snapshot_policy_schema.go
> +				helper.BoolDefault(false),
Please check this for setting up the default values https://developer.hashicorp.com/terraform/plugin/framework/resources/default

2024-01-30 19:28 UTC, shenda1 commented on powerflex/provider/snapshot_policy_schema.go
> +		"volume_id": schema.SetAttribute{
volume_ids?

2024-01-30 19:30 UTC, shenda1 commented on examples/resources/powerflex_snapshot_policy/resource.tf
> +# name and protection_domain_id is the required parameter to create or update
verify once if protection_domain_id is needed.

2024-01-30 19:31 UTC, shenda1 commented on examples/resources/powerflex_snapshot_policy/resource.tf
> +# To check which attributes of the fault set can be updated, please refer Product Guide in the documentation
fault set -> snapshot policy

2024-01-30 19:32 UTC, shenda1 commented on examples/resources/powerflex_snapshot_policy/resource.tf
> +# To import , check import.sh for more info
import.sh is missing

2024-01-30 19:33 UTC, shenda1 commented on powerflex/provider/snapshot_policy_resource_test.go
> +			// Create fault set Test
fault set -> snapshot policy. Applicable for all instances

2024-01-30 19:34 UTC, shenda1 requested changes
Please add coverage report

2024-02-01 12:23 UTC, AnikaAgiwal2711 commented on examples/resources/powerflex_snapshot_policy/resource.tf
> +Copyright (c) 2023 Dell Inc., or its subsidiaries. All Rights Reserved.
Done

2024-02-01 12:23 UTC, AnikaAgiwal2711 commented on powerflex/provider/snapshot_policy_resource_test.go
> +Copyright (c) 2023 Dell Inc., or its subsidiaries. All Rights Reserved.
Done

2024-02-01 12:24 UTC, AnikaAgiwal2711 commented on powerflex/provider/snapshot_policy_resource.go
> +Copyright (c) 2023 Dell Inc., or its subsidiaries. All Rights Reserved.
Done

2024-02-01 12:24 UTC, AnikaAgiwal2711 commented on powerflex/provider/snapshot_policy_resource.go
> +				"Error assigning volume to snapshot policy",
Handled the partial creation issue.

2024-02-01 12:25 UTC, AnikaAgiwal2711 commented on powerflex/provider/snapshot_policy_resource.go
> +	// upadting the list of volumes assinged to the state
Done

2024-02-01 12:25 UTC, AnikaAgiwal2711 commented on powerflex/provider/snapshot_policy_resource.go
> +	for _, v := range volumes {
Moved the logic to the update state function

2024-02-01 12:25 UTC, AnikaAgiwal2711 commented on powerflex/provider/snapshot_policy_resource.go
> +	for _, v := range volumes {
Moved the logic to the update state function

2024-02-01 12:25 UTC, AnikaAgiwal2711 commented on powerflex/provider/snapshot_policy_schema.go
> +				helper.BoolDefault(false),
Changed

2024-02-01 12:26 UTC, AnikaAgiwal2711 commented on powerflex/provider/snapshot_policy_schema.go
> +		"volume_id": schema.SetAttribute{
Changed

2024-02-01 12:26 UTC, AnikaAgiwal2711 commented on examples/resources/powerflex_snapshot_policy/resource.tf
> +# To check which attributes of the fault set can be updated, please refer Product Guide in the documentation
Updated

2024-02-01 12:26 UTC, AnikaAgiwal2711 commented on examples/resources/powerflex_snapshot_policy/resource.tf
> +# To import , check import.sh for more info
added

2024-02-01 12:27 UTC, AnikaAgiwal2711 commented
<img width="720" alt="image" src="https://github.com/dell/terraform-provider-powerflex/assets/118799587/1798f0a7-598b-4b44-97f9-5ab37548ca7f">

2024-02-02 05:00 UTC, shenda1 commented on powerflex/provider/snapshot_policy_resource.go
> +	// updating the detils to the state
details

2024-02-02 05:02 UTC, shenda1 commented on powerflex/provider/snapshot_policy_resource_test.go
> +	volume_ids = ["edd2fb3100000007","edd2fb3200000008"]
Don't use hardcoded values. Applicable for all instances.

2024-02-02 05:03 UTC, shenda1 reviewed
@AnikaAgiwal2711 Minor comments else looks good. Is it possible to increase the coverage > 80% ? Also github actions did not run (probably because of the conflict)

2024-02-06 05:33 UTC, Krunal-Thakkar commented
Please resolve conflicts

2024-02-06 15:00 UTC, AnikaAgiwal2711 commented on powerflex/provider/snapshot_policy_resource_test.go
> +	volume_ids = ["edd2fb3100000007","edd2fb3200000008"]
Done

2024-02-06 15:03 UTC, AnikaAgiwal2711 commented on powerflex/provider/snapshot_policy_resource.go
> +	// updating the detils to the state
Done

2024-02-06 15:04 UTC, AnikaAgiwal2711 commented
> @AnikaAgiwal2711 Minor comments else looks good. Is it possible to increase the coverage > 80% ? Also github actions did not run (probably because of the conflict)

I've added all the corner cases what all was possible. I don't think it will cross 80%

2024-02-07 09:23 UTC, AnikaAgiwal2711 commented
run e2e test

2024-02-07 09:25 UTC, Krunal-Thakkar commented
run e2e test

2024-02-07 09:32 UTC, AnikaAgiwal2711 commented
run e2e test

2024-02-07 09:59 UTC, AnikaAgiwal2711 commented
run e2e test

2024-02-07 10:06 UTC, AnikaAgiwal2711 commented
run e2e test

2024-02-07 10:51 UTC, shenda1 approved these changes

2024-02-07 11:24 UTC, merged