Fr datasource
dell/terraform-provider-powerflex pull request #182
Opened 2024-05-21 10:58 UTC by AnikaAgiwal2711

# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 80% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-05-21 11:11 UTC, shenda1 commented on docs/data-sources/firmware_repository.md
> +# Copyright (c) 2023-2024 Dell Inc., or its subsidiaries. All Rights Reserved.
2024

2024-05-21 11:14 UTC, shenda1 commented on powerflex/helper/firmware_repository_helper.go
> +// // newtypes.StringList converts list of client.types.String to list of models.types.String
remove if not required

2024-05-21 11:16 UTC, shenda1 commented on powerflex/provider/firmware_repository_datasource_schema.go
> +Copyright (c) 2023-2024 Dell Inc., or its subsidiaries. All Rights Reserved.
2024

2024-05-21 11:17 UTC, shenda1 commented on powerflex/provider/firmware_repository_datasource_schema.go
> +// FaultSetDataSourceSchema defines the schema for Fault Set datasource
FaultSetDataSourceSchema ->  FirmwareRepositoryDataSourceSchema

2024-05-21 11:18 UTC, shenda1 commented on powerflex/provider/firmware_repository_datasource_test.go
> +	firmware_repository_ids = ["8aaa3fda8f5c2609018f854266e12865", "8aaa3fda8f5c2609018f857b6c0d2ede"]
Don't hardcode the IDs or Names

2024-05-21 11:19 UTC, shenda1 commented on powerflex/provider/firmware_repository_datasource_test.go
> +				Config: ProviderConfigForTesting + FRDataSourceConfig1,
Please add assertion statements

2024-05-21 11:20 UTC, shenda1 requested changes
Add the coverage report

2024-05-22 13:28 UTC, AnikaAgiwal2711 commented
![image](https://github.com/dell/terraform-provider-powerflex/assets/118799587/ac8c5dd0-14af-4bf1-acc9-bfbb8b0c24b5)

2024-05-22 13:29 UTC, AnikaAgiwal2711 commented
![image (6)](https://github.com/dell/terraform-provider-powerflex/assets/118799587/c43e65df-5119-4ef7-8dd1-c59610c16683)

2024-05-27 16:22 UTC, AnikaAgiwal2711 commented on docs/data-sources/firmware_repository.md
> +# Copyright (c) 2023-2024 Dell Inc., or its subsidiaries. All Rights Reserved.
Done

2024-05-27 16:22 UTC, AnikaAgiwal2711 commented on powerflex/helper/firmware_repository_helper.go
> +// // newtypes.StringList converts list of client.types.String to list of models.types.String
Done

2024-05-27 16:22 UTC, AnikaAgiwal2711 commented on powerflex/provider/firmware_repository_datasource_schema.go
> +Copyright (c) 2023-2024 Dell Inc., or its subsidiaries. All Rights Reserved.
Done

2024-05-27 16:22 UTC, AnikaAgiwal2711 commented on powerflex/provider/firmware_repository_datasource_schema.go
> +// FaultSetDataSourceSchema defines the schema for Fault Set datasource
Done

2024-05-27 16:23 UTC, AnikaAgiwal2711 commented on powerflex/provider/firmware_repository_datasource_test.go
> +	firmware_repository_ids = ["8aaa3fda8f5c2609018f854266e12865", "8aaa3fda8f5c2609018f857b6c0d2ede"]
Done

2024-05-27 16:26 UTC, AnikaAgiwal2711 commented
run e2e test

2024-05-28 10:56 UTC, Krunal-Thakkar commented
run e2e test

2024-05-28 10:58 UTC, Krunal-Thakkar commented
run e2e test

2024-05-28 11:09 UTC, shenda1 commented
run e2e test

2024-05-28 11:23 UTC, Krunal-Thakkar commented
run e2e test

2024-05-28 12:54 UTC, AnikaAgiwal2711 commented on powerflex/provider/firmware_repository_resource_test.go
> +Copyright (c) 2023-2024 Dell Inc., or its subsidiaries. All Rights Reserved.
Done

2024-05-28 12:55 UTC, AnikaAgiwal2711 commented on powerflex/provider/firmware_repository_datasource_test.go
> +Copyright (c) 2023-2024 Dell Inc., or its subsidiaries. All Rights Reserved.
Done

2024-05-28 14:00 UTC, AnikaAgiwal2711 commented
run e2e test

2024-05-29 04:13 UTC, shenda1 approved these changes

2024-05-29 04:40 UTC, Krunal-Thakkar approved these changes

2024-05-29 04:41 UTC, merged